# Generated by Django 3.2.7 on 2021-10-01 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0002_alter_topic_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='cuser',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
